# Generated by Django 5.0 on 2024-01-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moderateur',
            table='moderateurs',
        ),
    ]
