# Generated by Django 5.0 on 2023-12-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yourmodel',
            table='myapp_yourmodel',
        ),
    ]
