# Generated by Django 5.0 on 2023-12-26 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_yourmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='yourmodel',
            table=None,
        ),
    ]
