# Generated by Django 5.0 on 2024-01-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_moderateur_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moderateur',
            table='moderators',
        ),
    ]
