# Generated by Django 5.0 on 2023-12-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_userindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userindex',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
