# Generated by Django 5.0 on 2024-01-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_moderateur_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderateur',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
