# Generated by Django 5.0 on 2023-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_userindex_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userindex',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
