# Generated by Django 5.0 on 2023-12-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_moderateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderateur',
            name='uid',
        ),
    ]
