# Generated by Django 5.0 on 2023-12-30 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_remove_moderateur_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderateur',
            old_name='name',
            new_name='username',
        ),
    ]
