# Generated by Django 5.0 on 2023-12-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Refrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicationDate', models.DateField()),
                ('title', models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='autors',
            field=models.ManyToManyField(to='UserPart.author'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='institution',
            field=models.ManyToManyField(to='UserPart.institution'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='refrences',
            field=models.ManyToManyField(to='UserPart.refrence'),
        ),
    ]
