# Generated by Django 5.0 on 2023-12-23 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPart', '0002_institution_refrence_metadata_autors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
    ]
