# Generated by Django 5.0 on 2024-01-31 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='None', max_length=255)),
                ('name', models.CharField(default='None', max_length=255)),
                ('address', models.TextField(default='None')),
                ('post_code', models.CharField(default='None', max_length=10)),
                ('country', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(default='None', max_length=255)),
                ('title', models.TextField(default='None')),
                ('pub_date', models.CharField(default='None', max_length=10)),
                ('keywords', models.TextField(default='[]')),
                ('abstract', models.TextField(default='None')),
                ('authors', models.ManyToManyField(to='article.author')),
                ('institutions', models.ManyToManyField(to='article.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob', models.TextField(default='None')),
                ('meta_data', models.OneToOneField(default={}, on_delete=django.db.models.deletion.CASCADE, to='article.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_year', models.CharField(default='None', max_length=12)),
                ('article_title', models.TextField(default='None')),
                ('reference_id', models.TextField(default='None')),
                ('volume', models.CharField(default='None', max_length=10)),
                ('raw_text', models.CharField(default='NONE', max_length=256)),
                ('authors', models.ManyToManyField(related_name='references', to='article.author')),
            ],
        ),
        migrations.AddField(
            model_name='metadata',
            name='references',
            field=models.ManyToManyField(related_name='citations', to='article.reference'),
        ),
        migrations.CreateModel(
            name='UnPublishedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('meta_data', models.OneToOneField(default={}, on_delete=django.db.models.deletion.CASCADE, to='article.metadata')),
            ],
        ),
    ]
