<<<<<<< HEAD
# Generated by Django 5.0 on 2024-02-01 11:07

import moderator.models
=======
# Generated by Django 5.0 on 2023-12-26 19:14

import moderator.models
import uuid
>>>>>>> MAHRAZABDELRAHMEN
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='mod', max_length=255)),
                ('last_name', models.CharField(default='mod', max_length=255)),
                ('email', models.EmailField(default='abc@abc.com', max_length=254, unique=True)),
                ('mod_id', models.UUIDField(default=moderator.models.ModAttributesUtil.generate_unique_mod_id, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(default=moderator.models.ModAttributesUtil.password, max_length=255)),
            ],
            options={
                'permissions': [('Can access moderator pages', 'mod_only_perm'), ('Can access non user pages', 'mod_admin_only')],
=======
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(default="mod", max_length=255)),
                ("last_name", models.CharField(default="mod", max_length=255)),
                (
                    "email",
                    models.EmailField(
                        default="abc@abc.com", max_length=254, unique=True
                    ),
                ),
                (
                    "mod_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "password",
                    models.CharField(
                        default=moderator.models.ModAttributesUtil.password,
                        max_length=255,
                    ),
                ),
            ],
            options={
                "abstract": False,
>>>>>>> MAHRAZABDELRAHMEN
            },
        ),
    ]
