# Generated by Django 5.0 on 2023-12-26 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moderator",
            name="mod_id",
        ),
    ]
