# Generated by Django 5.0 on 2023-12-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$n0VFyJyJ3JypOLjuBUVXiO$ctHJaVDd5wMDfKC38Im77oNIAL4ri+qZYarK4LAbUg8=",
                max_length=255,
            ),
        ),
    ]
