# Generated by Django 5.0 on 2023-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0002_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$HYluNFlikhQkVtggeelnPm$VdQ5tefvi5SmZsHz5VMz4FfPuKe9/zX/JEtTKUMlO8s=",
                max_length=255,
            ),
        ),
    ]
