# Generated by Django 5.0 on 2023-12-26 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0002_remove_moderator_mod_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="mod_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
