# Generated by Django 5.0 on 2023-12-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0003_moderator_last_login_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$6lSeHDQBisCjPq8ivAdRLU$I23/bBAmOwqf+mXitgS1B/R79mYTBm+wv2lvVGi+bAc=",
                max_length=255,
            ),
        ),
    ]
