# Generated by Django 5.0 on 2023-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0003_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$lAISV6Doo45e7NCEShFcJy$TRgDPj4rLH9iDgNZvG5awmMWWlFT7u7TTfTND2Ctwkw=",
                max_length=255,
            ),
        ),
    ]
