# Generated by Django 5.0 on 2023-12-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0004_alter_moderator_email_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$VyspjiXPFKphFtjAdtOjey$VGhhDpOqSv1Z0e/L3em3vhnLY1DmwNuklhZIxbnXWWw=",
                max_length=255,
            ),
        ),
    ]
