# Generated by Django 5.0 on 2023-12-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0005_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$sirovs0eWA19i1PJ2nZN2c$1UwWL/HuDQhdkUDVi2E82rvxZt4y4nFCddGiZ9v38kk=",
                max_length=255,
            ),
        ),
    ]
