# Generated by Django 5.0 on 2023-12-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "moderator",
            "0006_alter_moderator_first_name_alter_moderator_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moderator",
            name="mod_id",
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$xFuNE7SuctQsG0oW9SbnYi$N+XyB5ErdDTswtxHp76kAfJXpyijP/pVFB7XvUMgLu4=",
                max_length=255,
            ),
        ),
    ]
