# Generated by Django 5.0 on 2023-12-26 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0007_remove_moderator_mod_id_alter_moderator_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="mod_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="email",
            field=models.EmailField(default="ex@gil.com", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="first_name",
            field=models.CharField(default="mod", max_length=255),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="last_name",
            field=models.CharField(default="mod", max_length=255),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$l0OSxM8E2KZG7dTk1z1ckc$ZkxINZKPin8mqv5G1+tZUTMOWsFdLqRSQ1Q+JntzPAw=",
                max_length=255,
            ),
        ),
    ]
