# Generated by Django 5.0 on 2023-12-26 18:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0009_alter_moderator_mod_id_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="mod_id",
            field=models.UUIDField(
                default=uuid.UUID("056cd4cc-0700-4d1c-8ec3-ad6edd69dcd7"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$b7qh32VQ1lKLygKdLFyrz9$Hfs4G2C9FQKFZW0FKO0mVenVmMQ0LmmVX7wDTyj74oI=",
                max_length=255,
            ),
        ),
    ]
