# Generated by Django 5.0 on 2023-12-26 18:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0011_alter_moderator_mod_id_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="mod_id",
            field=models.UUIDField(
                default=uuid.UUID("1c56d884-c039-4aa7-8bca-815736ce0174"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$OHINH0pflZsa6n4hpTNmxF$anwqjJFAFn4+cN/8RXjDuqPVVQLurLBC1iJ1ht7fee4=",
                max_length=255,
            ),
        ),
    ]
