# Generated by Django 5.0 on 2023-12-26 18:37

import moderator.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0012_alter_moderator_mod_id_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="mod_id",
            field=models.UUIDField(
                default=moderator.models.ModAttributesUtil.generate_unique_mod_id,
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$wTyZia0WOaCxiDMOI1bPFV$5b2p9goIL5Q4mJ8bP9pHTJ7971YmQRxK7V0JIRs3yMI=",
                max_length=255,
            ),
        ),
    ]
