# Generated by Django 5.0 on 2023-12-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0013_alter_moderator_mod_id_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$wu7HP7kIOcgAMIS5Ok1C3h$lsqFUklmk6hBafkSuxbYCZwgT0+nXOuwFjlFZXGMJik=",
                max_length=255,
            ),
        ),
    ]
