# Generated by Django 5.0 on 2023-12-26 18:39

import moderator.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0014_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="mod_id",
            field=models.UUIDField(
                default=moderator.models.gen, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$f8DoAWwpxMzoGv3BedNUiE$RNDOqtBUa/3iIge05x8P1sVqEJzLxynHNvXwwb4If0Q=",
                max_length=255,
            ),
        ),
    ]
