# Generated by Django 5.0 on 2023-12-26 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderator", "0015_alter_moderator_mod_id_alter_moderator_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="mod_id",
            field=models.UUIDField(
                default=uuid.UUID("39a69129-11cb-400c-bf46-2d2f9574b5d2"),
                editable=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="password",
            field=models.CharField(
                default="pbkdf2_sha256$720000$oqs6TlXrEYlDO0W6S8jgu0$9AG6f16A6DMYkh09KXdrAVKm5WhWAkazHofduqk7esQ=",
                max_length=255,
            ),
        ),
    ]
